package hcux.eps.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.hand.hap.core.BaseConstants;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;

import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
import org.springframework.format.annotation.DateTimeFormat;

import java.math.BigDecimal;
import java.util.Date;

/**
 * @author yexiang.ren@hand-china.com
 * @description 挂账数据表
 */
@ExtensionAttribute(disable = true)
@Table(name = "HCUX_EPS_BILL")
public class EpsBill extends BaseDTO {

    public static final String FIELD_BILL_ID = "billId";
    public static final String FIELD_FUND_BALANCES_ID = "fundBalancesId";
    public static final String FIELD_PROJECT_NAME = "projectName";
    public static final String FIELD_ACCOUNTS = "accounts";
    public static final String FIELD_BALANCE_DATE = "balanceDate";
    public static final String FIELD_CURRENCY_CODE = "currencyCode";
    public static final String FIELD_REMAIN_AMOUNT = "remainAmount";
    public static final String FIELD_LOCAL_AMOUNT = "localAmount";
    public static final String FIELD_PARTY_NAME = "partyName";


    @Id
    @GeneratedValue
    private Long billId;//Id

    private Long fundBalancesId;//ERP视图ID，确定唯一

    @Length(max = 200)
    private String projectName;//项目号

    @Length(max = 200)
    private String accounts;//科目项

    @JsonFormat(pattern = BaseConstants.DATE_FORMAT, timezone = "GMT+8")
    @DateTimeFormat(pattern = BaseConstants.DATE_TIME_FORMAT)
    private Date balanceDate;//业务日期

    @Length(max = 200)
    private String currencyCode;//币种

    private Double remainAmount;//金额

    private Double localAmount;//折合金额

    @Length(max = 200)
    private String partyName;//往来方

    @Transient
    private String queryType; //查询类型（HAP、门户、微信）

    @Transient
    private String projectNameFrom; //项目号从

    @Transient
    private String projectNameTo; //项目号至

    @Transient
    private String totalAmount; // 总计金额

    @Transient
    private BigDecimal totalRemainAmount;//金额总和

    public Long getBillId() {
        return billId;
    }

    public void setBillId(Long billId) {
        this.billId = billId;
    }

    public void setFundBalancesId(Long fundBalancesId) {
        this.fundBalancesId = fundBalancesId;
    }

    public Long getFundBalancesId() {
        return fundBalancesId;
    }

    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    public String getProjectName() {
        return projectName;
    }

    public void setAccounts(String accounts) {
        this.accounts = accounts;
    }

    public String getAccounts() {
        return accounts;
    }

    public void setBalanceDate(Date balanceDate) {
        this.balanceDate = balanceDate;
    }

    public Date getBalanceDate() {
        return balanceDate;
    }

    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode;
    }

    public String getCurrencyCode() {
        return currencyCode;
    }

    public void setRemainAmount(Double remainAmount) {
        this.remainAmount = remainAmount;
    }

    public Double getRemainAmount() {
        return remainAmount;
    }

    public void setLocalAmount(Double localAmount) {
        this.localAmount = localAmount;
    }

    public Double getLocalAmount() {
        return localAmount;
    }

    public void setPartyName(String partyName) {
        this.partyName = partyName;
    }

    public String getPartyName() {
        return partyName;
    }

    public String getQueryType() {
        return queryType;
    }

    public void setQueryType(String queryType) {
        this.queryType = queryType;
    }

    public String getProjectNameFrom() { return projectNameFrom; }

    public void setProjectNameFrom(String projectNameFrom) { this.projectNameFrom = projectNameFrom; }

    public String getProjectNameTo() { return projectNameTo; }

    public void setProjectNameTo(String projectNameTo) { this.projectNameTo = projectNameTo; }

    public String getTotalAmount() { return totalAmount; }

    public void setTotalAmount(String totalAmount) { this.totalAmount = totalAmount; }

    public BigDecimal getTotalRemainAmount() {
        return totalRemainAmount;
    }

    public void setTotalRemainAmount(BigDecimal totalRemainAmount) {
        this.totalRemainAmount = totalRemainAmount;
    }

}
