package hcux.eps.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.hand.hap.core.BaseConstants;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;

import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
import org.springframework.format.annotation.DateTimeFormat;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

/**
 * 收款流水表
 */
@ExtensionAttribute(disable = true)
@Table(name = "HCUX_EPS_CASH_FLOW")
public class EpsCashFlow extends BaseDTO {

    public static final String FIELD_CASH_FLOW_ID = "cashFlowId";
    public static final String FIELD_RECEIPT_NUMBER = "receiptNumber";
    public static final String FIELD_RECEIPT_DATE = "receiptDate";
    public static final String FIELD_DESCRIPTION = "description";
    public static final String FIELD_CURRENCY_CODE = "currencyCode";
    public static final String FIELD_AMOUNT = "amount";
    public static final String FIELD_EXCHANGE_RATE = "exchangeRate";
    public static final String FIELD_NATURE_AMOUNT = "natureAmount";
    public static final String FIELD_BANK_NAME = "bankName";
    public static final String FIELD_SERIAL_NUMBER = "serialNumber";
    public static final String FIELD_RETURN_DATE = "returnDate";
    public static final String FIELD_RETURN_AMOUNT = "returnAmount";
    public static final String FIELD_DELETE_FLAG = "deleteFlag";


    @Id
    @GeneratedValue
    private Long cashFlowId;

    @Length(max = 150)
    private String receiptNumber;//收款编号
    @JsonFormat(pattern = BaseConstants.DATE_FORMAT, timezone = "GMT+8")
    @DateTimeFormat(pattern = BaseConstants.DATE_TIME_FORMAT)
    private Date receiptDate;//收款日期

    @Length(max = 1000)
    private String description;//付款方

    @Length(max = 150)
    private String currencyCode;//币种

    private BigDecimal amount;//收款金额

    private BigDecimal exchangeRate;//汇率

    private BigDecimal natureAmount;//收款本位币

    @Length(max = 150)
    private String bankName;//银行

    @Length(max = 150)
    private String serialNumber;//系列号

    @JsonFormat(pattern = BaseConstants.DATE_FORMAT, timezone = "GMT+8")
    @DateTimeFormat(pattern = BaseConstants.DATE_TIME_FORMAT)
    private Date returnDate;//退款日期

    private Double returnAmount;//退款金额

    @Length(max = 1)
    private String deleteFlag;

    @Transient
    @JsonFormat(pattern = BaseConstants.DATE_FORMAT, timezone = "GMT+8")
    @DateTimeFormat(pattern = BaseConstants.DATE_TIME_FORMAT)
    private Date receiptDateFrom;//收款日期从

    @Transient
    @JsonFormat(pattern = BaseConstants.DATE_FORMAT, timezone = "GMT+8")
    @DateTimeFormat(pattern = BaseConstants.DATE_TIME_FORMAT)
    private Date receiptDateTo;//收款日期至

    @Transient
    @JsonFormat(pattern = BaseConstants.DATE_FORMAT, timezone = "GMT+8")
    @DateTimeFormat(pattern = BaseConstants.DATE_TIME_FORMAT)
    private Date returnDateFrom;//退款日期从

    @Transient
    @JsonFormat(pattern = BaseConstants.DATE_FORMAT, timezone = "GMT+8")
    @DateTimeFormat(pattern = BaseConstants.DATE_TIME_FORMAT)
    private Date returnDateTo;//退款日期至

    @Transient
    private BigDecimal amountFrom;//收款金额从

    @Transient
    private BigDecimal amountTo;//收款金额至

    @Transient
    private BigDecimal returnAmountFrom;//退款金额从

    @Transient
    private BigDecimal returnAmountTo;//退款金额至

    @Transient
    private BigDecimal totalReceipt;

    @Transient
    private BigDecimal totalNatureAmount;

    @Transient
    private BigDecimal totalReturnAmount;//退款金额总计

    @Transient
    private String stringTotalReturnAmount;//各种币制的退款金额合计

    @Transient
    private String stringTotalReceipt;//各种币制的收款金额合计

    @Transient
    private String queryType; //查询类型（HAP、门户、微信）

    @Transient
    private String userName; //接收微信传递的用户名

    @Transient
    private List<String> serialNumberList;//系列号集合

    public Long getCashFlowId() {
        return cashFlowId;
    }

    public void setCashFlowId(Long cashFlowId) {
        this.cashFlowId = cashFlowId;
    }

    public void setReceiptNumber(String receiptNumber) {
        this.receiptNumber = receiptNumber;
    }

    public String getReceiptNumber() {
        return receiptNumber;
    }

    public void setReceiptDate(Date receiptDate) {
        this.receiptDate = receiptDate;
    }

    public Date getReceiptDate() {
        return receiptDate;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode;
    }

    public String getCurrencyCode() {
        return currencyCode;
    }

    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    public String getBankName() {
        return bankName;
    }

    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber;
    }

    public String getSerialNumber() {
        return serialNumber;
    }

    public void setReturnDate(Date returnDate) {
        this.returnDate = returnDate;
    }

    public Date getReturnDate() {
        return returnDate;
    }

    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    public String getDeleteFlag() {
        return deleteFlag;
    }

    public Date getReceiptDateFrom() {
        return receiptDateFrom;
    }

    public void setReceiptDateFrom(Date receiptDateFrom) {
        this.receiptDateFrom = receiptDateFrom;
    }

    public Date getReceiptDateTo() {
        return receiptDateTo;
    }

    public void setReceiptDateTo(Date receiptDateTo) {
        this.receiptDateTo = receiptDateTo;
    }

    public Date getReturnDateFrom() {
        return returnDateFrom;
    }

    public void setReturnDateFrom(Date returnDateFrom) {
        this.returnDateFrom = returnDateFrom;
    }

    public Date getReturnDateTo() {
        return returnDateTo;
    }

    public void setReturnDateTo(Date returnDateTo) {
        this.returnDateTo = returnDateTo;
    }

    public BigDecimal getAmount() {
        return amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    public BigDecimal getExchangeRate() {
        return exchangeRate;
    }

    public void setExchangeRate(BigDecimal exchangeRate) {
        this.exchangeRate = exchangeRate;
    }

    public BigDecimal getNatureAmount() {
        return natureAmount;
    }

    public void setNatureAmount(BigDecimal natureAmount) {
        this.natureAmount = natureAmount;
    }

    public Double getReturnAmount() {
        return returnAmount;
    }

    public void setReturnAmount(Double returnAmount) {
        this.returnAmount = returnAmount;
    }

    public BigDecimal getAmountFrom() {
        return amountFrom;
    }

    public void setAmountFrom(BigDecimal amountFrom) {
        this.amountFrom = amountFrom;
    }

    public BigDecimal getAmountTo() {
        return amountTo;
    }

    public void setAmountTo(BigDecimal amountTo) {
        this.amountTo = amountTo;
    }

    public BigDecimal getReturnAmountFrom() {
        return returnAmountFrom;
    }

    public void setReturnAmountFrom(BigDecimal returnAmountFrom) {
        this.returnAmountFrom = returnAmountFrom;
    }

    public BigDecimal getReturnAmountTo() {
        return returnAmountTo;
    }

    public void setReturnAmountTo(BigDecimal returnAmountTo) {
        this.returnAmountTo = returnAmountTo;
    }

    public BigDecimal getTotalReceipt() {
        return totalReceipt;
    }

    public void setTotalReceipt(BigDecimal totalReceipt) {
        this.totalReceipt = totalReceipt;
    }

    public BigDecimal getTotalNatureAmount() {
        return totalNatureAmount;
    }

    public void setTotalNatureAmount(BigDecimal totalNatureAmount) {
        this.totalNatureAmount = totalNatureAmount;
    }

    public BigDecimal getTotalReturnAmount() {
        return totalReturnAmount;
    }

    public void setTotalReturnAmount(BigDecimal totalReturnAmount) {
        this.totalReturnAmount = totalReturnAmount;
    }

    public String getStringTotalReturnAmount() {
        return stringTotalReturnAmount;
    }

    public void setStringTotalReturnAmount(String stringTotalReturnAmount) {
        this.stringTotalReturnAmount = stringTotalReturnAmount;
    }

    public String getStringTotalReceipt() {
        return stringTotalReceipt;
    }

    public void setStringTotalReceipt(String stringTotalReceipt) {
        this.stringTotalReceipt = stringTotalReceipt;
    }

    public String getQueryType() { return queryType; }

    public void setQueryType(String queryType) { this.queryType = queryType; }

    public String getUserName() { return userName; }

    public void setUserName(String userName) { this.userName = userName; }

    public List<String> getSerialNumberList() { return serialNumberList; }

    public void setSerialNumberList(List<String> serialNumberList) { this.serialNumberList = serialNumberList; }
}
