package hcux.cs.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import hcux.core.util.HcuxConstant;
import org.hibernate.validator.constraints.Length;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

@ExtensionAttribute(disable = true)
@Table(name = "HCUX_CS_CONTRACT_OUT")
public class CsContractOut extends BaseDTO {

    public static final String FIELD_CONTRACT_OUT_ID = "contractOutId";
    public static final String FIELD_HEADER_ID = "headerId";
    public static final String FIELD_LINE_ID = "lineId";
    public static final String FIELD_ORG_NAME = "orgName";
    public static final String FIELD_CUST_PO_NUMBER = "custPoNumber";
    public static final String FIELD_ITEM_CODE = "itemCode";
    public static final String FIELD_ITEM_NAME = "itemName";
    public static final String FIELD_OUT_QUANTITY = "outQuantity";
    public static final String FIELD_DELETE_FLAG = "deleteFlag";
    public static final String FIELD_LINE_CATEGORY_CODE = "lineCategoryCode";
    public static final String FIELD_UOM_CODE = "uomCode";


    @Id
    @GeneratedValue
    private Long contractOutId;//表ID，主键，供其他表做外键

    private Long headerId;//ERP视图ID，多个ID组合确定唯一

    private Long lineId;//ERP视图ID，多个ID组合确定唯一

    @Length(max = 200)
    private String orgName;//业务实体

    @Length(max = 200)
    private String custPoNumber;//销售合同编号

    @Length(max = 200)
    private String itemCode;//物料编码

    @Length(max = 200)
    private String itemName;//品名规格

    private Float outQuantity;//出库数量

    @Length(max = 1)
    private String deleteFlag = HcuxConstant.YES_NO.N;

    @Length(max = 200)
    private String lineCategoryCode;//订单行类型

    @Length(max = 200)
    private String uomCode;//单位


    public Long getContractOutId() {
        return contractOutId;
    }

    public void setContractOutId(Long contractOutId) {
        this.contractOutId = contractOutId;
    }

    public Long getHeaderId() {
        return headerId;
    }

    public void setHeaderId(Long headerId) {
        this.headerId = headerId;
    }

    public Long getLineId() {
        return lineId;
    }

    public void setLineId(Long lineId) {
        this.lineId = lineId;
    }

    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    public String getOrgName() {
        return orgName;
    }

    public void setCustPoNumber(String custPoNumber) {
        this.custPoNumber = custPoNumber;
    }

    public String getCustPoNumber() {
        return custPoNumber;
    }

    public void setItemCode(String itemCode) {
        this.itemCode = itemCode;
    }

    public String getItemCode() {
        return itemCode;
    }

    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    public String getItemName() {
        return itemName;
    }

    public void setOutQuantity(Float outQuantity) {
        this.outQuantity = outQuantity;
    }

    public Float getOutQuantity() {
        return outQuantity;
    }

    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    public String getDeleteFlag() {
        return deleteFlag;
    }

    public String getLineCategoryCode() { return lineCategoryCode; }

    public void setLineCategoryCode(String lineCategoryCode) { this.lineCategoryCode = lineCategoryCode; }

    public String getUomCode() { return uomCode; }

    public void setUomCode(String uomCode) { this.uomCode = uomCode; }
}
