package hcux.cs.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.hand.hap.core.BaseConstants;
import com.hand.hap.mybatis.annotation.Condition;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "HCUX_CS_OUTBOUND_ORDER")
public class CsOutboundOrder extends BaseDTO {

    public static final String FIELD_ORDER_ID = "orderId";
    public static final String FIELD_ORDER_TYPE = "orderType";
    public static final String FIELD_INV = "inv";
    public static final String FIELD_TOTAL_INV = "totalInv";
    public static final String FIELD_INV_PRINT = "invPrint";
    public static final String FIELD_CUSTOMER_NAME = "customerName";
    public static final String FIELD_INVOICE_NO = "invoiceNo";
    public static final String FIELD_INVOICE_TYPE = "invoiceType";
    public static final String FIELD_EXPECT_INVOICE_DATE = "expectInvoiceDate";
    public static final String FIELD_EFFECTIVE_DATE = "effectiveDate";
    public static final String FIELD_PO_PROECT_NUM = "poProectNum";
    public static final String FIELD_RECEIPTER_CODE = "receipterCode";
    public static final String FIELD_RECEIPTER = "receipter";
    public static final String FIELD_INVOICE_METHOD = "invoiceMethod";
    public static final String FIELD_WAREHOUSE_COST = "warehouseCost";
    public static final String FIELD_READ_DATE = "readDate";
    public static final String FIELD_READ_FLAG = "readFlag";
    public static final String FIELD_INV_STATUS = "invStatus";
    public static final String FIELD_DEPARTMENT = "department";


    @Id
    @GeneratedValue
    private Long orderId; //表ID，主键，供其他表做外键

    @Length(max = 200)
    private String orderType; //订单类型

    @Length(max = 200)
    private String inv; //仓库

    @Length(max = 200)
    private String totalInv; //总仓库

    @Length(max = 200)
    private String invPrint; //仓库(打印)

    @Length(max = 200)
    @Condition(operator = LIKE)
    private String customerName; //客户名称

    @Length(max = 200)
    private String invoiceNo; //出库编号

    @Length(max = 200)
    private String invoiceType; //出库单类型

    @DateTimeFormat(pattern = BaseConstants.DATE_TIME_FORMAT)
    @JsonFormat(pattern = BaseConstants.DATE_TIME_FORMAT, timezone = "GMT+8")
    private Date expectInvoiceDate; //预计出库日期

    @DateTimeFormat(pattern = BaseConstants.DATE_TIME_FORMAT)
    @JsonFormat(pattern = BaseConstants.DATE_TIME_FORMAT, timezone = "GMT+8")
    private Date effectiveDate; //有效日期

    @Length(max = 200)
    private String poProectNum; //采购项目号

    @Length(max = 200)
    private String receipterCode; //收货人编码

    @Length(max = 200)
    private String receipter; //收货人名称

    @Length(max = 200)
    private String invoiceMethod; //出库方式

    @Length(max = 200)
    private String warehouseCost; //出仓费用

    @DateTimeFormat(pattern = BaseConstants.DATE_TIME_FORMAT)
    @JsonFormat(pattern = BaseConstants.DATE_TIME_FORMAT, timezone = "GMT+8")
    private Date readDate; //记录读取时间

    @Length(max = 1)
    private String readFlag; //记录是否被成功读取

    @Length(max = 100)
    private String invStatus; //仓库订单状态

    @Length(max = 200)
    private String department; //部门

    @Transient
    private String itemDesc; //物料编码

    @Transient
    private Float invQty; //出库数量

    @Transient
    private Float actInvQty; //仓库实际出库数量

    @Transient
    @DateTimeFormat(pattern = BaseConstants.DATE_TIME_FORMAT)
    @JsonFormat(pattern = BaseConstants.DATE_TIME_FORMAT, timezone = "GMT+8")
    private Date expectDateFrom; //预计出库日期从

    @Transient
    @DateTimeFormat(pattern = BaseConstants.DATE_TIME_FORMAT)
    @JsonFormat(pattern = BaseConstants.DATE_TIME_FORMAT, timezone = "GMT+8")
    private Date expectDateTo; //预计出库日期至

    public void setOrderId(Long orderId){
        this.orderId = orderId;
    }

    public Long getOrderId(){
        return orderId;
    }

    public void setOrderType(String orderType){
        this.orderType = orderType;
    }

    public String getOrderType(){
        return orderType;
    }

    public void setInv(String inv){
        this.inv = inv;
    }

    public String getInv(){
        return inv;
    }

    public void setTotalInv(String totalInv){
        this.totalInv = totalInv;
    }

    public String getTotalInv(){
        return totalInv;
    }

    public void setInvPrint(String invPrint){
        this.invPrint = invPrint;
    }

    public String getInvPrint(){
        return invPrint;
    }

    public void setCustomerName(String customerName){
        this.customerName = customerName;
    }

    public String getCustomerName(){
        return customerName;
    }

    public void setInvoiceNo(String invoiceNo){
        this.invoiceNo = invoiceNo;
    }

    public String getInvoiceNo(){
        return invoiceNo;
    }

    public void setInvoiceType(String invoiceType){
        this.invoiceType = invoiceType;
    }

    public String getInvoiceType(){
        return invoiceType;
    }

    public void setExpectInvoiceDate(Date expectInvoiceDate){
        this.expectInvoiceDate = expectInvoiceDate;
    }

    public Date getExpectInvoiceDate(){
        return expectInvoiceDate;
    }

    public void setEffectiveDate(Date effectiveDate){
        this.effectiveDate = effectiveDate;
    }

    public Date getEffectiveDate(){
        return effectiveDate;
    }

    public void setPoProectNum(String poProectNum){
        this.poProectNum = poProectNum;
    }

    public String getPoProectNum(){
        return poProectNum;
    }

    public void setReceipterCode(String receipterCode) { this.receipterCode = receipterCode; }

    public String getReceipterCode() {return receipterCode; }

    public void setReceipter(String receipter){
        this.receipter = receipter;
    }

    public String getReceipter(){
        return receipter;
    }

    public void setInvoiceMethod(String invoiceMethod){
        this.invoiceMethod = invoiceMethod;
    }

    public String getInvoiceMethod(){
        return invoiceMethod;
    }

    public void setWarehouseCost(String warehouseCost){
        this.warehouseCost = warehouseCost;
    }

    public String getWarehouseCost(){
        return warehouseCost;
    }

    public void setReadDate(Date readDate){
        this.readDate = readDate;
    }

    public Date getReadDate(){
        return readDate;
    }

    public void setReadFlag(String readFlag){
        this.readFlag = readFlag;
    }

    public String getReadFlag(){
        return readFlag;
    }

    public void setInvStatus(String invStatus){
        this.invStatus = invStatus;
    }

    public String getInvStatus(){
        return invStatus;
    }

    public void setDepartment(String department) { this.department = department; }

    public String getDepartment() { return department; }

    public void setItemDesc(String itemDesc) { this.itemDesc = itemDesc; }

    public String getItemDesc() { return itemDesc; }

    public void setInvQty(Float invQty) { this.invQty = invQty; }

    public Float getInvQty() { return invQty; }

    public void setActInvQty(Float actInvQty) { this.actInvQty = actInvQty; }

    public Float getActInvQty() { return  actInvQty; }

    public void setExpectDateFrom(Date expectDateFrom) { this.expectDateFrom = expectDateFrom; }

    public Date getExpectDateFrom() { return expectDateFrom; }

    public void setExpectDateTo(Date expectDateTo) { this.expectDateTo = expectDateTo; }

    public Date getExpectDateTo() { return expectDateTo; }

    }
