package hcux.cs.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
@ExtensionAttribute(disable=true)
@Table(name = "HCUX_CS_OUTBOUND_TRANS")
public class CsOutboundTrans extends BaseDTO {

     public static final String FIELD_TRANS_ID = "transId";
     public static final String FIELD_ORDER_ID = "orderId";
     public static final String FIELD_DRIVER_NAME = "driverName";
     public static final String FIELD_ID_NUMBER = "idNumber";
     public static final String FIELD_TRANSPORT_NUM = "transportNum";
     public static final String FIELD_PLATE_NUMBER = "plateNumber";
     public static final String FIELD_CONTACT_INFO = "contactInfo";
     public static final String FIELD_ITEM_CODE = "itemCode";
     public static final String FIELD_ITEM_DESC = "itemDesc";
     public static final String FIELD_QUANTITY = "quantity";
     public static final String FIELD_PACK_CNT = "packCnt";
     public static final String FIELD_TANK_NUM = "tankNum";
     public static final String FIELD_REMARK = "remark";


     @Id
     @GeneratedValue
     private Long transId; //表ID，主键，供其他表做外键

     private Long orderId; //出库单头表HCUX_CS_OUTBOUND_ORDER.ORDER_ID

     @Length(max = 100)
     private String driverName; //司机姓名

     @Length(max = 50)
     private String idNumber; //身份证号

     @Length(max = 100)
     private String transportNum; //运输单号

     @Length(max = 100)
     private String plateNumber; //车船号

     @Length(max = 200)
     private String contactInfo; //联系方式

     @Length(max = 200)
     private String itemCode; //物料编码

     @Length(max = 2000)
     private String itemDesc; //品名

     private Float quantity; //数量

     private Float packCnt; //包数

     @Length(max = 100)
     private String tankNum; //仓库识别号

     @Length(max = 4000)
     private String remark; //备注


     public void setTransId(Long transId){
         this.transId = transId;
     }

     public Long getTransId(){
         return transId;
     }

     public void setOrderId(Long orderId){
         this.orderId = orderId;
     }

     public Long getOrderId(){
         return orderId;
     }

     public void setDriverName(String driverName){
         this.driverName = driverName;
     }

     public String getDriverName(){
         return driverName;
     }

     public void setIdNumber(String idNumber){
         this.idNumber = idNumber;
     }

     public String getIdNumber(){
         return idNumber;
     }

     public void setTransportNum(String transportNum){
         this.transportNum = transportNum;
     }

     public String getTransportNum(){
         return transportNum;
     }

     public void setPlateNumber(String plateNumber){
         this.plateNumber = plateNumber;
     }

     public String getPlateNumber(){
         return plateNumber;
     }

     public void setContactInfo(String contactInfo){
         this.contactInfo = contactInfo;
     }

     public String getContactInfo(){
         return contactInfo;
     }

     public void setItemCode(String itemCode){
         this.itemCode = itemCode;
     }

     public String getItemCode(){
         return itemCode;
     }

     public void setItemDesc(String itemDesc){
         this.itemDesc = itemDesc;
     }

     public String getItemDesc(){
         return itemDesc;
     }

     public void setQuantity(Float quantity){
         this.quantity = quantity;
     }

     public Float getQuantity(){
         return quantity;
     }

     public void setPackCnt(Float packCnt){
         this.packCnt = packCnt;
     }

     public Float getPackCnt(){
         return packCnt;
     }

     public void setTankNum(String tankNum){
         this.tankNum = tankNum;
     }

     public String getTankNum(){
         return tankNum;
     }

     public void setRemark(String remark){
         this.remark = remark;
     }

     public String getRemark(){
         return remark;
     }

     }
