package hcux.cs.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;

import javax.persistence.Table;

import com.hand.hap.system.dto.BaseDTO;

@ExtensionAttribute(disable = true)
@Table(name = "HCUX_CS_OUTBOUND_ITEM_FULL")
public class CsOutboundItemFull extends BaseDTO {

    public static final String FIELD_ITEM_ALL_ID = "itemAllId";
    public static final String FIELD_INVOICE_ID = "invoiceId";
    public static final String FIELD_INVOICE_NO = "invoiceNo";
    public static final String FIELD_ITEM_NO = "itemNo";
    public static final String FIELD_ITEM_DESC = "itemDesc";
    public static final String FIELD_EXCHANGE_QTY = "exchangeQty";
    public static final String FIELD_OUTBOUND_QTY = "outboundQty";
    public static final String FIELD_QUANTITY_PCS = "quantityPcs";
    public static final String FIELD_INVOICE_LINE_ID = "invoiceLineId";
    public static final String FIELD_UOM_CODE = "uomCode";
    public static final String FIELD_UNIT_OF_MEASURE = "unitOfMeasure";



    @Id
    @GeneratedValue
    private Long itemAllId; //表ID，主键，供其他表做外键

    private Long invoiceId; //出库单全量头表HCUX_CS_OUTBOUND_ORDER_ALL.INVOICE_ID

    @Length(max = 200)
    private String invoiceNo; //出库编号

    @Length(max = 200)
    private String itemNo; //物料编码

    @Length(max = 2000)
    private String itemDesc; //品名

    private Float exchangeQty; //件数

    private Float outboundQty; //出库数量

    private Float quantityPcs; //提单数量

    private Long invoiceLineId; //ERP视图ID,确定唯一

    @Length(max = 200)
    private String uomCode; //单位

    @Length(max = 200)
    private String unitOfMeasure; //单位（中文）



    public void setItemAllId(Long itemAllId) { this.itemAllId = itemAllId; }

    public Long getItemAllId() { return itemAllId; }

    public void setInvoiceId(Long invoiceId) { this.invoiceId = invoiceId; }

    public Long getInvoiceId() { return invoiceId; }

    public void setInvoiceNo(String invoiceNo) { this.invoiceNo = invoiceNo; }

    public String getInvoiceNo() { return invoiceNo; }

    public void setItemNo(String itemNo) { this.itemNo = itemNo; }

    public String getItemNo() { return itemNo; }

    public void setItemDesc(String itemDesc) { this.itemDesc = itemDesc; }

    public String getItemDesc() { return itemDesc; }

    public void setExchangeQty(Float exchangeQty) { this.exchangeQty = exchangeQty; }

    public Float getExchangeQty() { return exchangeQty; }

    public void setOutboundQty(Float outboundQty) { this.outboundQty = outboundQty; }

    public Float getOutboundQty() { return outboundQty; }

    public Float getQuantityPcs() { return quantityPcs; }

    public void setQuantityPcs(Float quantityPcs) { this.quantityPcs = quantityPcs; }

    public Long getInvoiceLineId() { return invoiceLineId; }

    public void setInvoiceLineId(Long invoiceLineId) { this.invoiceLineId = invoiceLineId; }

    public String getUomCode() { return uomCode; }

    public void setUomCode(String uomCode) { this.uomCode = uomCode; }

    public String getUnitOfMeasure() { return unitOfMeasure; }

    public void setUnitOfMeasure(String unitOfMeasure) { this.unitOfMeasure = unitOfMeasure; }

}
